-- • Create a function that returns all information from the artist details table for a given artist id, using a row variable.
-- • Create a function doing the same thing as above but using a record.
-- • Create a function that will return all rock songs, determined by the artist id, with all of the artist details.
-- • Create a function that returns the quantity of songs for a given album ID, only if the quantity is bigger than 5. If it is not, raise a notice. Use the if/else statement.
-- • Create a function that returns all artists that sang a song from a playlist with a certain id.